name=input("enter your name ")
branch=input("enter your branch ")
gender=input("enter your gender ")
college=input("enter your college ")
age=int(input("enter your age "))
print("Name is",name)
print("Branch is",branch)
print("Gender is",gender)
print("College is", college)
print("Age is",age)
